export {default as Navbar_Top} from './Components/Asosiy_components/Navbar_top/NavbarTop'
export {default as Navbar} from './Components/Asosiy_components/Navbar/Navbar'
export {default as Catigories} from "./Components/Home_components/Categorioes/Catigories"
export {default as Home} from "./Pages/Home/Home"
export {default as Header_Slider} from "./Components/Home_components/Header_Slider/Header_Slider"
export { default as Suggestions} from "./Components/Home_components/Suggestions/Suggestions"
export {default as Popular_categories} from "./Components/Home_components/Popular_categories/Popular_categories"
export {default as BarsCard} from "./Components/Asosiy_components/BarsCard/BarsCard"
export {default as Main_slider} from "./Components/Home_components/main_slider/main_slider"
export {default as Cheaper} from "./Components/Home_components/Cheaper/Cheaper"
export {default as Footer} from "./Components/Asosiy_components/Footer/Footer"
export {default as Recommend } from "./Components/Home_components/Recommend/Recommend"
export {default as Brands } from "./Components/Home_components/Brands/Brands"
export {default as Filtr} from "./Pages/Filtr/Filtr"
export {default as DataFilter} from "./Components/Filter_component/Data_Filter/Data_Filter"
export {default as FilterResult} from "./Components/Filter_component/Filter_rusult/Filter_rusult"
export {default as Favorites} from "./Pages/Favorites/Favorites"
export {default as Favorites_components} from "./Components/Favorites/Favorites"
export {default as Main_manu } from "./Components/Asosiy_components/Main_menu/Main_menu"
export {default as Filter_inside } from "./Pages/Filter_inside/Filter_inside"
export {default as Filter_inside_product_imeg} from "./Components/Filter_component/Filter_inside_product_imeg/Filter_inside_product_imeg"
export {default as Filter_inside_product_direction} from "./Components/Filter_component/Filter_inside_product_direction/Filter_inside_product_direction"
export {default as Praduct_Aboute} from "./Components/Filter_component/Praduct_aboute/Praduct_Aboute"
export {default as AStarter } from "./Components/Filter_component/AStarter/AStarter"
export {default as PageNoteFount } from "./Pages/PageNotFount/NotPage"
export {default as Search } from "./Pages/Search/Search"
export {default as SearchResult } from "./Components/Search_components/Search_result"
export {default as Login } from "./Pages/login/Login"
export {default as SignUp} from "./Pages/sign up/SignUp"
export {default as Cobinet } from "./Pages/PersonalCabinet/PersonalCabinet"
export {default as CategoryModal } from "./Components/Home_components/Categorioes/Catigories"
export {default as Media_modal } from "./Components/Home_components/Categorioes/Modal_media/Modal_media"
export {default as Purchase } from "./Pages/Purchase/Purchase" 
export {default as Models } from "./Components/Filter_component/Models/Models" 
export {default as Interest } from "./Components/Asosiy_components/interest/interest" 
export {default as PurchaseLeft } from "./Components/PurchaseComponents/PerchaseLeft/PurchaseLeft" 
export {default as PurchaseRight } from "./Components/PurchaseComponents/PerchaseRight/PurchaseRight" 
export {default as RecentlyViewed } from "./Components/Asosiy_components/RecentlyViewed/RecentlyViewed" 